---

on:
  push:
    branches: [devel]
  pull_request:
    branches: ["**"]
name: Test
jobs:
  test:
    env:
      GO111MODULE: "on"
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: make local-build
      - name: Test
        shell: bash
        run: |
           if [ "$RUNNER_OS" == "Windows" ]; then
                make local-test-windows
           else
                make local-test
           fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TKN }}
  staticcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17.x"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@2022.1.3
      - name: Run staticcheck
        run: staticcheck ./...
